REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB0 = 0
REDIS_DB1 = 1

IMAGE_WIDTH = 320
IMAGE_HEIGHT = 320
CROP_LR = IMAGE_HEIGHT // 2
CROP_T = 0
CROP_B = IMAGE_HEIGHT
IMAGE_CHANS = 3
IMAGE_DTYPE = "float32"

IMAGE_QUEUE = "image_queue"
BATCH_SIZE = 64
SERVER_SLEEP = 0
CLIENT_SLEEP = 0

MODEL_PTH = "./model/model.json"
WEIGHTS_PTH = "./model/weights.h5"
