REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB0 = 0
REDIS_DB1 = 1

IMAGE_WIDTH = 128
IMAGE_HEIGHT = 128
IMAGE_CHANS = 3
IMAGE_DTYPE = "float32"

IMAGE_QUEUE = "image_queue"
BATCH_SIZE = 32
SERVER_SLEEP = 0.25
CLIENT_SLEEP = 0.25

MODEL_PTH = "./model/model.json"
WEIGHTS_PTH = "./model/weights.h5"
